# Number of independent sample traces to generate
num_samples = 32
# Batch size of sample generation. If not provided, we do a single batch
batch_size = 256
# Number of sampling steps to take
num_steps = 256

# Which model to load (ema, best, last) 
model_type = "ema"
# Output directory for generations.
out_dir = "samples/noTe"
# Whether samples in out_dir should be replaced or added to
replace_samples = true
# Step scale
step_scale = 1.00
# ODE method
method = "midpoint"

[observation]
base_sim = "mcmc_reference/ref_3charge/normalized"
stddev = 1.0

[observation.fields]
B = {locs = "all", error_type = "relative"}
nu_an = {locs = "all", error_type = "relative"}